<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class Products extends Seeder
{
    public function run()
    {
        $rows = [
            // Gunpla (7)
            [
                'kode_product' => 'GUNPLA008',
                'nama_product' => 'RG Unicorn Gundam Perfectibility',
                'kategori'     => 'gunpla',
                'jumlah'       => 6,
                'kondisi'      => 'new',
                'deskripsi'    => 'Real Grade 1/144 — detail tinggi, cocok buat kolektor.',
                'is_active'    => 1,
                'harga'        => 1250000.00,
                'image'        => 'rg_unicorn_perfectibility.jpg',
            ],
            [
                'kode_product' => 'GUNPLA002',
                'nama_product' => 'RG Hi-Nu Gundam',
                'kategori'     => 'gunpla',
                'jumlah'       => 4,
                'kondisi'      => 'new',
                'deskripsi'    => 'Real Grade 1/144 — artikulasi mantap, part separation rapi.',
                'is_active'    => 1,
                'harga'        => 899000.00,
                'image'        => 'rg_hi_nu.jpg',
            ],
            [
                'kode_product' => 'GUNPLA003',
                'nama_product' => 'HG Gundam Aerial',
                'kategori'     => 'gunpla',
                'jumlah'       => 12,
                'kondisi'      => 'new',
                'deskripsi'    => 'High Grade 1/144 — gampang dirakit, cocok pemula.',
                'is_active'    => 1,
                'harga'        => 289000.00,
                'image'        => 'hg_aerial.jpg',
            ],
            [
                'kode_product' => 'GUNPLA004',
                'nama_product' => 'MG Barbatos (Used Complete)',
                'kategori'     => 'gunpla',
                'jumlah'       => 2,
                'kondisi'      => 'used',
                'deskripsi'    => 'Master Grade 1/100 — kondisi used, part lengkap, minus box.',
                'is_active'    => 1,
                'harga'        => 750000.00,
                'image'        => 'mg_barbatos_used.jpg',
            ],
            [
                'kode_product' => 'GUNPLA005',
                'nama_product' => 'HG Zaku II (Green)',
                'kategori'     => 'gunpla',
                'jumlah'       => 9,
                'kondisi'      => 'new',
                'deskripsi'    => 'HG klasik — build cepat, enak buat custom weathering.',
                'is_active'    => 1,
                'harga'        => 159000.00,
                'image'        => 'hg_zaku2_green.jpg',
            ],
            [
                'kode_product' => 'GUNPLA006',
                'nama_product' => 'SDCS RX-78-2 Gundam',
                'kategori'     => 'gunpla',
                'jumlah'       => 15,
                'kondisi'      => 'new',
                'deskripsi'    => 'SD Cross Silhouette — lucu, poseable, cocok hadiah.',
                'is_active'    => 1,
                'harga'        => 129000.00,
                'image'        => 'sdcs_rx782.jpg',
            ],
            [
                'kode_product' => 'GUNPLA007',
                'nama_product' => 'MGEX Strike Freedom Gundam',
                'kategori'     => 'gunpla',
                'jumlah'       => 1,
                'kondisi'      => 'new',
                'deskripsi'    => 'MGEX premium — detail, gimmick, dan presence maksimal.',
                'is_active'    => 1,
                'harga'        => 3299000.00,
                'image'        => 'mgex_strike_freedom.jpg',
            ],

            // TCG (6)
            [
                'kode_product' => 'TCG001',
                'nama_product' => 'Pokemon TCG Booster Pack (Random)',
                'kategori'     => 'tcg',
                'jumlah'       => 30,
                'kondisi'      => 'new',
                'deskripsi'    => 'Booster pack acak — peluang dapat rare/holo.',
                'is_active'    => 1,
                'harga'        => 45000.00,
                'image'        => 'pokemon_booster_random.jpg',
            ],
            [
                'kode_product' => 'TCG002',
                'nama_product' => 'Pokemon TCG ETB (Elite Trainer Box)',
                'kategori'     => 'tcg',
                'jumlah'       => 5,
                'kondisi'      => 'new',
                'deskripsi'    => 'ETB lengkap — booster, sleeve, dice, dan box storage.',
                'is_active'    => 1,
                'harga'        => 799000.00,
                'image'        => 'pokemon_etb.jpg',
            ],
            [
                'kode_product' => 'TCG003',
                'nama_product' => 'One Piece Card Game Starter Deck',
                'kategori'     => 'tcg',
                'jumlah'       => 8,
                'kondisi'      => 'new',
                'deskripsi'    => 'Starter deck — langsung bisa main, cocok pemula.',
                'is_active'    => 1,
                'harga'        => 189000.00,
                'image'        => 'opcg_starter_deck.jpg',
            ],
            [
                'kode_product' => 'TCG004',
                'nama_product' => 'Yu-Gi-Oh! Booster Pack',
                'kategori'     => 'tcg',
                'jumlah'       => 20,
                'kondisi'      => 'new',
                'deskripsi'    => 'Booster YGO — koleksi kartu meta & collectible.',
                'is_active'    => 1,
                'harga'        => 35000.00,
                'image'        => 'yugioh_booster.jpg',
            ],
            [
                'kode_product' => 'TCG005',
                'nama_product' => 'Pokemon Single Card (Used - Near Mint)',
                'kategori'     => 'tcg',
                'jumlah'       => 10,
                'kondisi'      => 'used',
                'deskripsi'    => 'Single card kondisi near mint — cocok buat upgrade deck.',
                'is_active'    => 1,
                'harga'        => 99000.00,
                'image'        => 'pokemon_single_nm.jpg',
            ],
            [
                'kode_product' => 'TCG006',
                'nama_product' => 'Card Sleeve (Standard 66x91mm)',
                'kategori'     => 'tcg',
                'jumlah'       => 40,
                'kondisi'      => 'new',
                'deskripsi'    => 'Sleeve standar — lindungi kartu dari gores & debu.',
                'is_active'    => 1,
                'harga'        => 25000.00,
                'image'        => 'sleeve_standard.jpg',
            ],

            // Figures (6)
            [
                'kode_product' => 'FIG001',
                'nama_product' => 'Action Figure — Mecha Pilot (1/12)',
                'kategori'     => 'figure',
                'jumlah'       => 7,
                'kondisi'      => 'new',
                'deskripsi'    => 'Figure 1/12 — artikulasi tinggi, aksesoris lengkap.',
                'is_active'    => 1,
                'harga'        => 399000.00,
                'image'        => 'figure_mecha_pilot.jpg',
            ],
            [
                'kode_product' => 'FIG002',
                'nama_product' => 'Nendoroid Style — Space Explorer',
                'kategori'     => 'figure',
                'jumlah'       => 3,
                'kondisi'      => 'new',
                'deskripsi'    => 'Chibi figure — faceplate extra, pose lucu.',
                'is_active'    => 1,
                'harga'        => 650000.00,
                'image'        => 'nendo_space_explorer.jpg',
            ],
            [
                'kode_product' => 'FIG003',
                'nama_product' => 'Scale Figure — Cyber Samurai (Used)',
                'kategori'     => 'figure',
                'jumlah'       => 1,
                'kondisi'      => 'used',
                'deskripsi'    => 'Scale figure used — kondisi bagus, ada minor scratch.',
                'is_active'    => 1,
                'harga'        => 850000.00,
                'image'        => 'scale_cyber_samurai_used.jpg',
            ],
            [
                'kode_product' => 'FIG004',
                'nama_product' => 'Figure Stand Base (Clear)',
                'kategori'     => 'figure',
                'jumlah'       => 25,
                'kondisi'      => 'new',
                'deskripsi'    => 'Stand base bening — buat pose dinamis, stabil.',
                'is_active'    => 1,
                'harga'        => 25000.00,
                'image'        => 'figure_stand_clear.jpg',
            ],
            [
                'kode_product' => 'FIG005',
                'nama_product' => 'Mini Figure — Mascot Set (4pcs)',
                'kategori'     => 'figure',
                'jumlah'       => 9,
                'kondisi'      => 'new',
                'deskripsi'    => 'Set 4 mini figure — cocok pajangan meja kerja.',
                'is_active'    => 1,
                'harga'        => 179000.00,
                'image'        => 'mini_mascot_set.jpg',
            ],
            [
                'kode_product' => 'FIG006',
                'nama_product' => 'Figure Display Case (Medium)',
                'kategori'     => 'figure',
                'jumlah'       => 2,
                'kondisi'      => 'new',
                'deskripsi'    => 'Display case — jaga figure dari debu, tampil rapi.',
                'is_active'    => 1,
                'harga'        => 299000.00,
                'image'        => 'display_case_medium.jpg',
            ],

            // Tools (3)
            [
                'kode_product' => 'TOOLS001',
                'nama_product' => 'Nipper Cutter (Single Blade)',
                'kategori'     => 'tools',
                'jumlah'       => 14,
                'kondisi'      => 'new',
                'deskripsi'    => 'Nipper single blade — potong runner lebih bersih.',
                'is_active'    => 1,
                'harga'        => 159000.00,
                'image'        => 'nipper_single_blade.jpg',
            ],
            [
                'kode_product' => 'TOOLS002',
                'nama_product' => 'Hobby Knife + 5 Blades',
                'kategori'     => 'tools',
                'jumlah'       => 18,
                'kondisi'      => 'new',
                'deskripsi'    => 'Cutter presisi — buat trimming nub dan detail kecil.',
                'is_active'    => 1,
                'harga'        => 49000.00,
                'image'        => 'hobby_knife_set.jpg',
            ],
            [
                'kode_product' => 'TOOLS003',
                'nama_product' => 'Sanding Sponge Set (5pcs)',
                'kategori'     => 'tools',
                'jumlah'       => 22,
                'kondisi'      => 'new',
                'deskripsi'    => 'Sponge grit campur — haluskan permukaan sebelum paint.',
                'is_active'    => 1,
                'harga'        => 39000.00,
                'image'        => 'sanding_sponge_set.jpg',
            ],

            // Paints (3)
            [
                'kode_product' => 'PAINTS001',
                'nama_product' => 'Acrylic Paint Set (6 colors)',
                'kategori'     => 'paints',
                'jumlah'       => 11,
                'kondisi'      => 'new',
                'deskripsi'    => 'Cat acrylic — cocok untuk detail painting & weathering ringan.',
                'is_active'    => 1,
                'harga'        => 119000.00,
                'image'        => 'acrylic_paint_set.jpg',
            ],
            [
                'kode_product' => 'PAINTS002',
                'nama_product' => 'Primer Spray (Grey) 200ml',
                'kategori'     => 'paints',
                'jumlah'       => 0,
                'kondisi'      => 'new',
                'deskripsi'    => 'Primer grey — bantu cat nempel, hasil lebih rata.',
                'is_active'    => 1,
                'harga'        => 89000.00,
                'image'        => 'primer_spray_grey.jpg',
            ],
            [
                'kode_product' => 'PAINTS003',
                'nama_product' => 'Top Coat Matte 170ml',
                'kategori'     => 'paints',
                'jumlah'       => 5,
                'kondisi'      => 'new',
                'deskripsi'    => 'Finishing matte — kurangi glossy, tampilan lebih realistis.',
                'is_active'    => 1,
                'harga'        => 95000.00,
                'image'        => 'topcoat_matte.jpg',
            ],
        ];

        $this->db->table('products')->insertBatch($rows);
    }
}
